# -*- coding: utf-8 -*-
"""temp3.py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qjh77W-wjYaj9Lo3X1er6FiYDjXxr2ZR
"""

from googletrans import Translator

def translate_to_hinglish(sentence):
    translator = Translator()
    result = translator.translate(sentence,src='en',dest='hi')
    return result.text

if __name__ == "__main__":
    english_sentence = input("Enter an English sentence: ")
    hinglish_translation = translate_to_hinglish(english_sentence)
    print(f"Hinglish Translation: {hinglish_translation}")