# -*- coding: utf-8 -*-
"""temp2.py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qjh77W-wjYaj9Lo3X1er6FiYDjXxr2ZR
"""

from translate import Translator
import random

def translate_random_words_to_hindi(english_sentence, num_words_to_translate):
    try:
        # Initialize a translator for English to Hindi
        translator = Translator(to_lang="hi")

        # Split the sentence into words
        words = english_sentence.split()

        # Randomly select words to translate
        words_to_translate = random.sample(words, num_words_to_translate)

        # Initialize a list to store the translated words
        translated_words = []

        # Iterate through the words in the sentence
        for word in words:
            # Check if the current word should be translated
            if word in words_to_translate:
                # Translate the word to Hindi
                translated_word = translator.translate(word)
                # Append the translated word to the list
                translated_words.append(translated_word)
            else:
                # If the word is not selected for translation, append it as is
                translated_words.append(word)

        # Reconstruct the sentence with translated and non-translated words
        translated_sentence = ' '.join(translated_words)

        return translated_sentence
    except Exception as e:
        return str(e)

if __name__ == "__main__":
    # Input an English sentence
    english_sentence = input("Enter an English sentence: ")

    # Define the number of words to randomly translate
    num_words_to_translate = 2  # You can adjust this as needed

    # Call the function to randomly translate words
    hindi_translation = translate_random_words_to_hindi(english_sentence, num_words_to_translate)

    # Print the translated Hindi sentence
    print("Hindi Translation:", hindi_translation)